# Generated by Django 3.1 on 2020-09-12 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_cv'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cv',
        ),
    ]
