# Generated by Django 3.1 on 2020-09-16 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_video'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Video',
        ),
    ]
