# Generated by Django 3.1 on 2020-09-19 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_events'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Events',
            new_name='Event',
        ),
    ]
