# Generated by Django 3.1 on 2020-09-19 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20200919_1141'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
