# Generated by Django 3.1.1 on 2020-09-23 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='website_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
