# Generated by Django 3.1.1 on 2020-09-26 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_event_website_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='PastEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=255)),
                ('header_image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('event_date', models.CharField(max_length=30)),
                ('event_location', models.CharField(max_length=100)),
                ('event_description', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='event',
            name='website_url',
        ),
    ]
