# Generated by Django 3.1.1 on 2020-09-27 12:00

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_event_website_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='body',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
