# Generated by Django 3.1.1 on 2020-10-03 17:26

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pastevent',
            name='event_description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
