# Generated by Django 3.1.1 on 2020-10-05 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20201003_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='header_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/newsletter'),
        ),
        migrations.CreateModel(
            name='NewsletterImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/newsletter')),
                ('newsletter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.newsletter')),
            ],
        ),
    ]
