# Generated by Django 3.1.1 on 2020-10-27 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_auto_20201015_0650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pastevent',
            name='event_date',
            field=models.DateField(blank=True, null=True, verbose_name='MM/DD/YYYY'),
        ),
    ]
