# Generated by Django 3.1.1 on 2020-10-27 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_auto_20201027_0349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pastevent',
            name='event_date',
            field=models.CharField(max_length=30),
        ),
    ]
