# Generated by Django 3.1.1 on 2020-10-28 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_auto_20201027_0352'),
    ]

    operations = [
        migrations.AddField(
            model_name='pastevent',
            name='order_date',
            field=models.DateField(blank=True, null=True, verbose_name='MM/DD/YYYY'),
        ),
    ]
